### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by xxlio109** [Tollainmear/KaroglanSignEditor#1]
Sponge:  spongeforge-1.12.2-2611-7.1.0-BETA-2963
forge:   forge-1.12.2-14.23.2.2611-universal
plugin:  KaroglanSignEditor-3.0

https://gist.github.com/xxlio109/0c22ed69934409a7748a3c1eac52c5f0

**Comment by Tollainmear** [comment]
我将会尽快修复这个问题

**Comment by Tollainmear** [comment]
此问题已经在最新发布的3.1中得到了解决，感谢您的支持~！
