### ISSUE TITLE
A few language suggestions

### ISSUE THREAD

**Issue by Aaron1011** [Tollainmear/KaroglanSignEditor#3]
This looks like a great plugin!

I have a few suggestions for the Github and Ore pages:

* On the Ore page and the Github repository desscription, 'Sign edition' should be changed to 'Sign editing' - the word 'edition' is unrelated to editing.
* On the Ore page, the sentence 'KSE will convenient for you! would be better written as 'KSE will be convenient for you!'
* On the Ore page, the sentence 'you will never need to replace a sign which only need to fix a mistake at single line!' could be better written as 'you will never need to replace a sign if you only need to fix a mistake on a single line!'

**Comment by Tollainmear** [comment]
Thank you vary much!
I'm happy to accept your suggestion! And I will make rectification as soon as possible.

**Comment by Tollainmear** [comment]
I hope the mistakes was revised now, and I should thank you again, as my first foreign language teacher ;)
